### ISSUE TITLE
supplements db no longer hosted at eveem

### ISSUE THREAD

**Issue by lsankar4033** [eveem-org/panoramix#14]
Currently having trouble getting started because this fetch fails: https://github.com/eveem-org/panoramix/blob/master/utils/supplement.py#L193

Would it be possible to share a zip of the supplements db somewhere else? in the meanwhile, i can just create an empty supplements.db locally, but it'd be nice to work with the ones you already have :)

**Comment by ytrezq** [comment]
@lsankar4033 : by creating an empty sample locally, do you mean that you understand the format inside the zip file ?

Because most projects like this are using https://www.4byte.directory.

**Comment by lsankar4033** [comment]
I just created an empty sqlite db with the same table structure (informed from the queries in panoramix) and it works fine without function names. Building off of 4bytes makes sense going forward though.

**Comment by ytrezq** [comment]
@lsankar4033 : hemm, no. Don’t close this. You may have understood the table structure but no me. Nor do I understand where to write such file. Can you please share it with me ?

**Comment by ytrezq** [comment]
@lsankar4033 : please !

**Comment by palkeo** [comment]
I made a fork where I committed a proper supplements.db (as an xz-compressed file that gets decompressed when panoramix runs):
https://github.com/palkeo/panoramix

The supplements.db I have is from when eveem was up, and this one has not been updated in a while, though. I'm thinking about a way to regenerate an updated one.

**Comment by ytrezq** [comment]
@palkeo it simply turns out Panoramix had everything.

    from utils.supplement import crawl_abis_from_cache
    crawl_abis_from_cache()

and it adds the abi files present in the `cache_abi` directory.

**Comment by kolinko** [comment]
Eveem.org was down briefly, I restarted it, so you should be able to fetch it now no problem :)

**Comment by kolinko** [comment]
@ytrezq as for crawl_abis_from_cache, it will make the supplement from your local abis, which will miss a ton of function definitions, so fetching it from eveem or palkeo's repo will be much better.

(and thanks @palkeo  for stepping in here with your repo)
