### ISSUE TITLE
.)

### ISSUE THREAD

**Issue by FernandabyeC** [eveem-org/panoramix#175]

**Comment by FernandabyeC** [comment]
> ```
>           0x71C7656EC7ab88b098defB751B7401B5f6d8976F.csv](https://github.com/eveem-org/panoramix/files/13834154/export-internal-tx-0x71C7656EC7ab88b098defB751B7401B5f6d8976F.csv)
> ```
> 
> _Publicado originalmente por@FernandabyeCen el [#167 (comentario)](https://github.com/eveem-org/panoramix/issues/167#issuecomment-1877558830)_

**Comment by FernandabyeC** [comment]
https://github.com/eveem-org/panoramix/files/13834154/export-internal-tx-0x71C7656EC7ab88b098defB751B7401B5f6d8976F.csv

**Comment by BrodysgotMs** [comment]
Decompile [0xB93aa27cA30a2D76549151a30C7Bfc11A3E97F95]
