### ISSUE TITLE
Feature request: generate solidity code

### ISSUE THREAD

**Issue by ggrieco-tob** [eveem-org/panoramix#2]
I wonder how far is Panoramix from generating Solidity code that can be compiled in solc. This feature could improve testing of the decompiled code, since the bytecode and its recompiled version can be differentially tested. Is that something you discarded a possible feature or it is planed eventually?

Keep up the hard work!

**Comment by kolinko** [comment]
I'm happy you like Panoramix! :)

As for the Solidity code, and code that can be recompiled, there are a few ways of approaching that:

- Writing a recompiler/interpreter of the .json form ( that is, from https://eveem.org/json/0x06012c8cf97BEaD5deAe237070F9587f8E7A266d into the bytecode)

This is actually quite feasible and quite possible. I definitely wouldn't trust such produced bytecode in production becaause Panoramix still has a bunch of bugs that cause it to decompile incorrectly at times, BUT it would be immensely useful for testing the decompiler itself. With such an interpreter/recompiler, we could re-run a history of all Ethereum transactions and see how many of them produce different results compared to the original ones. This would be the best metric for accuracy of the decompilation process

- Changing output from Python'esque pseudocode to Solidity pseudocode

This too is feasible and doable, although I'm definitely not attempting that. I absolutely hate the aesthetics of Solidity ;) Also, if you want to have the decompiled bytecode as readable as possible, sticking to a strict solidity syntax will be counter-productive - there are multiple statement kinds that are right now very readable in Panoramix, but would be way less so if it was Solidity.

- The thing you actually asked, which is recompilable and readable solidity bytecode

This would be extremely difficult, if not impossible even. For starters, Solidity doesn't allow direct memory access, so you would need do do a ton of hacking around the language to make it work. Most of the work spent on Panoramix, I spent trying to simplify/remove all the direct memory access statements, but it is very hard.

Then, you have multiple statements (like typecastings), that Panoramix produces, but Solidity would never allow. You would need to add extra code to make it go through solc.

And don't get me even started on storages... :)

In general, it would be a crazy-difficult thing, and if someone has skills and time to do it, there are many other things in Panoramix that would be more useful to add :)
