### ISSUE TITLE
supplement.zip not hosted on http://eveem.org/static/supplement.zip

### ISSUE THREAD

**Issue by Foristkirito** [eveem-org/panoramix#25]

**Comment by Danilo-caio-da-silva-vieira** [comment]
> 

]-/Danilo+}}}plataforma§→→→general}><
Software↑→※←bloquear//do**Wi-Fi[>>>_comandoA#Zdanilocaioplataformageneral/dasilvadanilocaiodasilvavieira@gmail.com![facebook_1600967971201_6714946365481936310.jpg](https://user-images.githubusercontent.com/75276078/106235827-4860cb80-61da-11eb-9479-abce4822b572.jpg)[]()****

**Comment by kolinko** [comment]
It should be fine now. The eveem.org server was down for a while.

**Comment by tarrencev** [comment]
@kolinko seems it might be down again?

**Comment by ByteSecurity** [comment]
> @kolinko seems it might be down again?

Like you said

**Comment by nosshar** [comment]
Is it possible to download this database from another hosting?
Host seems to be unavailable again

**Comment by timeeeee** [comment]
For anyone who finds themselves here, try https://github.com/palkeo/panoramix :)
