### ISSUE TITLE
can i use this tool generate abi just from bytecode?

### ISSUE THREAD

**Issue by mxito3** [eveem-org/panoramix#6]

**Comment by kolinko** [comment]
Yes, you can! :) Eveem.org has it implemented as you can see here:

https://eveem.org/abi/0x06012c8cf97BEaD5deAe237070F9587f8E7A266d

Pasting the code that generates ABI on Eveem. It's a part of a bigger whole, so you can't run it directly, but with a few fixes you should be able to run it.

```
def main(data=None, addr=None):

    if data == None:
        assert addr != None

        with open(f'../panoramix/cache_pan/{addr[:5]}/{addr}.json') as f:
            data = f.read()

    data = json.loads(data)
    addr = data['addr']
    print('\nExperimental auto-generated ABI')
    for k in ['addr', 'network']:
        v = data[k]
        if k!='functions':
            print(f'{k}: {COLOR_BLUE}{v}{ENDC}')

    print('')
    print('Please note:')
    print('- function parameter names may be off')
    if 'tuple' in str(data['functions']):
        print('- tuple parameters are not handled properly')
#    print('- names of the following functions were not found: ')
    print()

    res = []

    problems = []

    funcs = data['functions']

    for fname in data['problems']:
        funcs.append({
                'name': fname,
                'hash': '0x00000000',
            })

    for f in funcs:

#        'const' -> pure
#        'nonpayable' -> nonpayable
#        'payable' -> payable

        name = f['name']
        if 'unknown' in name and '?' in name:
            problems.append(f['hash'])
            continue

        name, params = name.split('(')
        params = params[:-1].split(', ')

        if '0x' not in f['hash']:
            assert f['name'] == '_fallback()'

            func = {
                'type': 'fallback',
            }

        else:

            func = {
                'type': 'function',
                'name': name,
                'inputs': []
            }


        if 'const' in f and f['const']:
            func['stateMutability'] = 'pure'

        # todo: handle stateMutability: 'view'

        elif 'payable' in f and f['payable']:
            func['stateMutability'] = 'payable'

        elif 'hash' != '0x00000000':
            func['stateMutability'] = 'nonpayable'

        fparams = []
        for p in params:
            if p == '': 
                continue

            if ' ' not in p:
                func['inputs'].append(p)
            else:
                ptype, pname = p.split(' ')
                pname = pname[1:] # remove leading '_'

                func['inputs'].append({
                        'name': pname,
                        'type': ptype})

        res.append(func)


    if len(problems) > 0:
        print('Functions not included')
        for p in problems:
            print('- ' + p)
        print('(no signatures found)')
        print()


    print(json.dumps(res, indent=4))
```

If you want to add it to panoramix (e.g. so it generates abi given a command line argument), I'll gladly accept a pull request :)

**Comment by mxito3** [comment]
> Yes, you can! :) Eveem.org has it implemented as you can see here:
> 
> https://eveem.org/abi/0x06012c8cf97BEaD5deAe237070F9587f8E7A266d
> 
> Pasting the code that generates ABI on Eveem. It's a part of a bigger whole, so you can't run it directly, but with a few fixes you should be able to run it.
> 
> ```
> def main(data=None, addr=None):
> 
>     if data == None:
>         assert addr != None
> 
>         with open(f'../panoramix/cache_pan/{addr[:5]}/{addr}.json') as f:
>             data = f.read()
> 
>     data = json.loads(data)
>     addr = data['addr']
>     print('\nExperimental auto-generated ABI')
>     for k in ['addr', 'network']:
>         v = data[k]
>         if k!='functions':
>             print(f'{k}: {COLOR_BLUE}{v}{ENDC}')
> 
>     print('')
>     print('Please note:')
>     print('- function parameter names may be off')
>     if 'tuple' in str(data['functions']):
>         print('- tuple parameters are not handled properly')
> #    print('- names of the following functions were not found: ')
>     print()
> 
>     res = []
> 
>     problems = []
> 
>     funcs = data['functions']
> 
>     for fname in data['problems']:
>         funcs.append({
>                 'name': fname,
>                 'hash': '0x00000000',
>             })
> 
>     for f in funcs:
> 
> #        'const' -> pure
> #        'nonpayable' -> nonpayable
> #        'payable' -> payable
> 
>         name = f['name']
>         if 'unknown' in name and '?' in name:
>             problems.append(f['hash'])
>             continue
> 
>         name, params = name.split('(')
>         params = params[:-1].split(', ')
> 
>         if '0x' not in f['hash']:
>             assert f['name'] == '_fallback()'
> 
>             func = {
>                 'type': 'fallback',
>             }
> 
>         else:
> 
>             func = {
>                 'type': 'function',
>                 'name': name,
>                 'inputs': []
>             }
> 
> 
>         if 'const' in f and f['const']:
>             func['stateMutability'] = 'pure'
> 
>         # todo: handle stateMutability: 'view'
> 
>         elif 'payable' in f and f['payable']:
>             func['stateMutability'] = 'payable'
> 
>         elif 'hash' != '0x00000000':
>             func['stateMutability'] = 'nonpayable'
> 
>         fparams = []
>         for p in params:
>             if p == '': 
>                 continue
> 
>             if ' ' not in p:
>                 func['inputs'].append(p)
>             else:
>                 ptype, pname = p.split(' ')
>                 pname = pname[1:] # remove leading '_'
> 
>                 func['inputs'].append({
>                         'name': pname,
>                         'type': ptype})
> 
>         res.append(func)
> 
> 
>     if len(problems) > 0:
>         print('Functions not included')
>         for p in problems:
>             print('- ' + p)
>         print('(no signatures found)')
>         print()
> 
> 
>     print(json.dumps(res, indent=4))
> ```
> 
> If you want to add it to panoramix (e.g. so it generates abi given a command line argument), I'll gladly accept a pull request :)

Thank you very much!

**Comment by mxito3** [comment]
And another question is what is the language this decompiled code used?
![image](https://user-images.githubusercontent.com/25946298/71010040-3632e380-2126-11ea-93dc-210a14843f09.png)

**Comment by ytrezq** [comment]
@mxito3 no you can’t as detection doesn’t works. #15
